# Generated by Django 2.2.7 on 2019-11-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
