# Generated by Django 3.0 on 2019-12-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20191128_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passed',
        ),
    ]
