# Generated by Django 3.0 on 2019-12-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20191205_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Course'),
        ),
    ]
