# Generated by Django 3.0 on 2019-12-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_user_test_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_exp',
            field=models.IntegerField(default=0),
        ),
    ]
