# Generated by Django 3.0 on 2019-12-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_profile_current_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='exp_per_question',
            new_name='exp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(default='NEWBIE', max_length=50, null=True),
        ),
    ]
